# Generated by Django 3.1.7 on 2021-03-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pessoa',
            table='pessoas',
        ),
    ]
